<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><!-- InstanceBegin template="/Templates/main.dwt" codeOutsideHTMLIsLocked="false" -->
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
        <!-- InstanceBeginEditable name="doctitle" -->
        <title>:: Eventapp Admin Panel::</title>
        <!-- InstanceEndEditable -->
        <?php $this->headLink()->appendStylesheet($this->baseUrl('css/style.css')) ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl('css/menushowhide1.css')) ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl('css/boxes.css')) ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl('css/menu-topbar.css')) ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl('css/menu-base.css')) ?>
        
        <link rel="stylesheet" href="<?php echo $this->baseUrl('datepicker/css/demos.css'); ?>"/>
        <link rel="stylesheet" href="<?php echo $this->baseUrl('datepicker/css/jquery.ui.all.css'); ?>"/>
        <link rel="stylesheet" href="<?php echo $this->baseUrl('datepicker/css/jquery.ui.base.css'); ?>"/>
        <link rel="stylesheet" href="<?php echo $this->baseUrl('datepicker/css/jquery.ui.core.css'); ?>"/>
        <link rel="stylesheet" href="<?php echo $this->baseUrl('datepicker/css/jquery.ui.datepicker.css'); ?>"/>
        <link rel="stylesheet" href="<?php echo $this->baseUrl('datepicker/css/jquery.ui.theme.css'); ?>"/>
        <link rel="stylesheet" href="<?php echo $this->baseUrl('css/colorbox.css'); ?>"/>
        <?= $this->cssHelper() ?>
        <script type="text/javascript">
	 
            function vis(id){
                document.getElementById(id).style.display='inline';
            }
            function invis(id){
                document.getElementById(id).style.display='none';
            }
        </script>

<!--        <script type="text/javascript" src="<?php //echo $this->baseUrl('js/jquery-1.js'); ?>"></script>-->
        <script type="text/javascript" src="<?php echo $this->baseUrl('datepicker/js/jquery-1.5.1.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery_002.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/stlib.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/menu.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery.colorbox.js'); ?>"></script>        
        <script type="text/javascript" src="<?php echo $this->baseUrl('datepicker/js/jquery.ui.core.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('datepicker/js/jquery.ui.widget.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('datepicker/js/jquery.ui.datepicker.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('datepicker/js/jquery.ui.datepicker.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery.validate.js'); ?>"></script>
        <script>
            $(function() {
                $( "#datepicker" ).datepicker();
                $(".example1").colorbox({iframe:true, width:"80%", height:"80%"});
            });     
        </script>
    </head>
    <?php if(isset($this->actionforgot)){  
?>
     <body style="background:url('<?php echo $this->baseUrl('images/bg1.jpg') . 'repeat-x'; ?>');  background-color:#F1F5FF;">
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td></td>
                </tr>
                <tr>
                    <td style="padding-top:100px;">
                        <table width="0%" border="0" align="center" cellpadding="0" cellspacing="0" style="background:url('<?php echo $this->baseUrl('images/login.jpg'); ?>') no-repeat; width:542px; height:257px;">
                            <tr>
                                <td>
                                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td height="225" valign="top">
                                                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                                    <tr>
                                                        <td height="35" align="center" class="login-hd">
                                                            <?php
                                                            if ($this->messages) {
                                                                foreach ($this->messages as $messages) {
                                                                    echo $messages;
                                                                }
                                                            } else {
                                                                echo 'Forgot Password ';
                                                            }
                                                            ?>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>                                                                
                                                            <?php echo $this->layout()->content ?>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td height="30" align="center" valign="middle" style="color:#d7e6ff"><a href="#" style="color:#d7e6ff">Copyright &copy; 2012</a> </td>
                                        </tr>
                                    </table>                                        
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td></td>
                </tr>
            </table>
        </body>
    <?php
        return;
        } ?>
    <?php if (isset($this->actionnm)) { ?>
        <body style="background:url('<?php echo $this->baseUrl('images/bg1.jpg') . 'repeat-x'; ?>');  background-color:#F1F5FF;">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td></td>
                </tr>
                <tr>
                    <td style="padding-top:100px;">
                        <table width="0%" border="0" align="center" cellpadding="0" cellspacing="0" style="background:url('<?php echo $this->baseUrl('images/login.jpg'); ?>') no-repeat; width:542px; height:257px;">
                            <tr>
                                <td>
                                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td height="225" valign="top">
                                                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                                    <tr>
                                                        <td height="35" align="center" class="login-hd">
                                                            <?php
                                                            if ($this->messages) {
                                                                foreach ($this->messages as $messages) {
                                                                    echo $messages;
                                                                }
                                                            } else {
                                                                echo 'Login to Admin Panel';
                                                            }
                                                            ?>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>                                                                
                                                            <?php echo $this->layout()->content ?>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td height="30" align="center" valign="middle" style="color:#d7e6ff"><a href="#" style="color:#d7e6ff">Copyright &copy; 2012</a></td>
                                        </tr>
                                    </table>                                        
                                </td>
                            </tr>
                        </table></td>
                </tr>
                <tr>
                    <td></td>
                </tr>
            </table>
        </body>
    <?php } else { ?>
        <body>
            <?php $session_user = new Zend_Session_Namespace('login'); ?>                
            <table width="" border="0" align="center" cellpadding="0" cellspacing="0" class="maintable">
                <tr>
                    <td class="topsection">
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td ><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td height="96" valign="middle">
                                  <a href="#"><img src="<?php echo $this->baseUrl('images/logo.gif'); ?>" hspace="20" /></a></td>
                                            <td class="p10"><table width="0%" height="70"  border="0" align="right" cellpadding="0" cellspacing="0">
                                                    <tr><?php $auth = Zend_Auth::getInstance();
                                                             $username = $auth->getIdentity()->username; ?>
                                                        <td height="24" valign="top" >Logged in as : <?php echo $username; ?> | <?php echo date('l jS \of F Y H:i:s A'); ?> |  <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'logout', 'module' => 'admin'), null, true); ?>">Log Out</a></td>
                                                    </tr>                                                        
                                                </table></td>
                                        </tr>
                                    </table></td>
                            </tr>
                            <tr>
                                <td align="center">
                                    <table width="98%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td width="8"></td>
                                            <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                                    <tr>
                                                        <td>
                                                            <script type="text/javascript">
                                                                ddlevelsmenu.setup("ddtopmenubar", "topbar") //ddlevelsmenu.setup("mainmenuid", "topbar|sidebar")
                                                            </script>
                                                            <div id="ddtopmenubar" class="mattblackmenu">
<!--                                                                <ul>
                                                <li > <a href="<?php //echo $this->url(array('controller'=>'index','action'=>'dashboard','module'=>'admin'));      ?>" >Dashboard</a> </li>
                                                                    <li> 
                                                                        <li> <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'manageusers', 'module' => 'admin'), '', true); ?>">Manage Users</a></li>
                                                                    </li>
                                                                    <li><ul id="ddsubmenu2" class="ddsubmenustyle">
                                                                            <li> <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'manageevents', 'module' => 'admin'), '', true); ?>">Manage Events</a></li>
                                                                        </ul>
                                                                    </li>
                                                                    <li><ul id="ddsubmenu8" class="ddsubmenustyle">
                                                                            <li > <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'changepassword', 'module' => 'admin'), '', true); ?>" >Change Password</a> </li>
                                                                        </ul>
                                                                    </li>
                                                                </ul>-->
 <ul>
                            <li > <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'manageusers', 'module' => 'admin'), '', true); ?>" >Manage Users</a> </li>
                            <li > <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'manageevents', 'module' => 'admin'), '', true); ?>" rel="ddsubmenu2">Manage Events</a> </li>
                            <li> <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'changepassword', 'module' => 'admin'), '', true); ?>" rel="ddsubmenu3" >change Password</a> </li>
                            <li style="padding:0PX; overflow:hidden;"><a href="#" style="padding:0PX; border:0PX;" rel="ddsubmenu0" ><img src="../images/blank.gif" width="0" height="0"  /></a> </li>
                            <!--<li> <a href="#"  rel="ddsubmenu4" style="margin-left:-6px;  " >Customers</a> </li>
                            <li > <a href="#" rel="ddsubmenu5" >Promotions</a> </li>
                            <li > <a href="#" rel="ddsubmenu6" >Newsletter</a> </li>
                            <li > <a href="#" rel="ddsubmenu7" >CMS</a> </li>
                            <li > <a href="#" rel="ddsubmenu8" >Reports</a> </li>
                            <li > <a href="#" rel="ddsubmenu9" >System</a> </li>-->
                          </ul>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                </table></td>
                                        </tr>
                                    </table></td>
                            </tr>
                            <tr>
                                <td height="27px"></td>
                            </tr>
                        </table>                            
                    </td>
                </tr>
                <tr>
                    <td ><table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td style="background:url(<?php echo $this->baseUrl('images/leftbg.gif'); ?> ) repeat-y; width:8px;"></td>
                                <!-- InstanceBeginEditable name="EditRegion2" -->
                                <td class="middsection"> <?php echo $this->layout()->content ?></td>
                                <!-- InstanceEndEditable -->
                                <td style="background:url(<?php echo $this->baseUrl('images/rightbg.gif'); ?>) repeat-y; width:8px;"></td>
                            </tr>
                        </table></td>
                </tr>
                <tr>
                    <td>
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td style="background:url(<?php echo $this->baseUrl('images/bt-left.gif'); ?> ) no-repeat; height:20px; width:8px; "></td>
                                <td style="background:url(<?php echo $this->baseUrl('images/bt-middle.gif'); ?> ) repeat-x; height:20px;" width="993"></td>
                                <td style="background:url(<?php echo $this->baseUrl('images/bt-left.gif'); ?> ) no-repeat; height:20px; width:8px; "></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td class="bottomsection" valign="middle">
                        <table width="98%" border="0" cellspacing="5" cellpadding="0" align="center">
                            <tr>
                                <td align="left" class="bottomlink">Copyright &copy; 2012</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </body>
    <?php } ?>
</html>
