<?php
use Zend\Session\Container;
//echo "url-".$this->url('admin', array('action' => 'success'));

error_log("Inside layout/login.phtml");

?>
 
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Memreas</title>

<!--Custom css -->
<link href="css/style.css" rel="stylesheet" type="text/css">
<link href="css/jquery.mCustomScrollbar.css" rel="stylesheet" />

<!--Bootstrap Css-->
<link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">

<!--jQuery Lybrary-->
<script src="js/jquery.js"></script>
<script src="js/modernizr.custom.17475.js"></script>

<!--Bootstrap jQuery-->
<script src="js/bootstrap.min.js"></script>

<!--Backgound Strecher-->
<script type="text/javascript" src="js/bgstretcher.js"></script>


<script type="text/javascript">
$(document).ready(function(){
$(document).bgStretcher({
			images: ['img/bg.jpg'],
			imageWidth: 1366, imageHeight: 700
		});
	});
</script>

</head>

<body>
<?php //var_dump($_SESSION) ?>
<?php //echo $this->content; ?>
<!-- Begin : Container -->
<div class="container">
  <!-- Begin : Header -->
  <div class="row-fluid">
  	<header>
      <div class="center_logo"><h1 id="logo"><a href="/admin">memreas</a></h1></div>
  	</header>
  </div>
  <!-- End : Header -->
  <!-- Begin : Content -->
  	<div class="row-fluid content">
    <div class="span6 memreas-big-logo"><img src="img/memreas_add.png"></div>
    <div class="span6">
    <div class="login_contents">
    <form name="users" method="POST" action="<?php echo $this->url('admin',array('action'=>'index'));?>">
    <ul>
    
    <li>
<form action="/admin" method="post" name="user" id="user">
    <input name="username"type="text" class="input" value="username" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'username')this.value = '';"/>
    <input name="password"type="password"  class="input" value="password" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'password')this.value = '';"/>
    </li>
    <li>

	<input type="submit" class="login-btn" value="login">
    
      <a href="#" class="forgot-password">forgot your password?</a>
    </li>
    </ul>
    </form>
    </div>
    
    <div class="signin_contents">
    <ul>
    <li>
    <div class="signup_heading">
      <p>Sign Up</p>
    </div>
    </li>
    <li>
    <figure class="profile_picture"><output id="list"></output></figure>
    <div class="file_upload">Choose Profile Picture <input id="file" type="file" name="file" /></div>
   <script>
	if (window.FileReader) {
      function handleFileSelect(evt) {
        var files = evt.target.files;
        var f = files[0];
        var reader = new FileReader();
		
          reader.onload = (function(theFile) {
            return function(e) {
              document.getElementById('list').innerHTML = ['<img src="', e.target.result,'" title="', theFile.name, '" width="50"/>'].join('');
            };
          })(f);
    
          reader.readAsDataURL(f);
      }
	 } else {
	  alert('This browser does not support FileReader');
	}
    
      document.getElementById('file').addEventListener('change', handleFileSelect, false);
    </script>
<script type="text/javascript" charset="utf-8">
    jQuery('#file').css('opacity',0);  
</script>
    </li>
    <li>
    <input name="input" class="signup_textfields"type="text" value="Your Email" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'Your Email')this.value = '';"/>
    <input name="input" class="signup_textfields"type="text" value="User Name" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'User Name')this.value = '';"/>
    <input name="input"type="text" class="signup_textfields" onFocus="if(this.value == 'Password')this.value = '';" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" value="Password"/>
    <input name="input" class="signup_textfields"type="text" value="Verify Password" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'Verify Password')this.value = '';"/>
    </li>
    
    <li>
    	<input id="demo_box_2" class="css-checkbox" type="checkbox" checked="checked" />
		<label for="demo_box_2" name="demo_lbl_2" class="css-label">legal disclaimer </label>
    </li>
    <li>
    <input type="button" class="sign-btn" value="Create an account">
    </li>
    
    </ul>
    </div>
    </div>
    </div>
  <!-- End : Content -->
</div>
<footer>&copy; 2013 memreas, llc. All rights reserved.</footer>
<!-- End : Container -->
</body>
</html>
