<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>:: Eventapp Login ::</title>

<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/style.css');
        ?>
</head>

<body style="background:url(<?php echo $this->basePath();?>/images/bg1.jpg) repeat-x;">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td></td>
  </tr>
  <tr>
    <td style="padding-top:100px;">
	<table width="0%" border="0" align="center" cellpadding="0" cellspacing="0" <?php echo 'style="background:url('.$this->basePath().'/images/login.jpg) no-repeat; width:542px; height:257px;" ';?>>
      <tr>
        <td>
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td height="225" valign="top">
                <?php echo $this->content; ?>

            </td>
          </tr>
          <tr>
            <td height="30" align="center" valign="middle" style="color:#d7e6ff">&nbsp;</td>
          </tr>
        </table></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td></td>
  </tr>
</table>
</body>
</html>
