<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><!-- InstanceBegin template="/Templates/main.dwt" codeOutsideHTMLIsLocked="false" -->
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
        <!-- InstanceBeginEditable name="doctitle" -->
        <title></title>
        <!-- InstanceEndEditable -->
        <?php echo $this->headTitle('Eventapp Admin Panel') ?>

        <?php // echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/menushowhide1.css')
                ->prependStylesheet($this->basePath() . '/css/boxes.css')
                ->prependStylesheet($this->basePath() . '/css/menu-topbar.css')
                ->prependStylesheet($this->basePath() . '/css/menu-base.css')
                ->prependStylesheet($this->basePath() . '/datepicker/css/demos.css')
                ->prependStylesheet($this->basePath() . '/datepicker/css/jquery.ui.all.css')
                ->prependStylesheet($this->basePath() . '/datepicker/css/jquery.ui.base.css')
                ->prependStylesheet($this->basePath() . '/datepicker/css/jquery.ui.core.css')
                ->prependStylesheet($this->basePath() . '/datepicker/css/jquery.ui.datepicker.css')
                ->prependStylesheet($this->basePath() . '/datepicker/css/jquery.ui.theme.css')
                ->prependStylesheet($this->basePath() . '/css/colorbox.css');
                ?>
       <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') 
            ?>
      
        <script type="text/javascript">
	 
            function vis(id){
                document.getElementById(id).style.display='inline';
            }
            function invis(id){
                document.getElementById(id).style.display='none';
            }
        </script>

<!--        <script type="text/javascript" src="<?php //echo $this->baseUrl('js/jquery-1.js'); ?>"></script>-->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') 
                ->prependFile($this->basePath() .'/datepicker/js/jquery-1.5.1.js')
        ->prependFile($this->basePath() .'/js/jquery_002.js')
        ->prependFile($this->basePath() .'/js/stlib.js')
        ->prependFile($this->basePath() .'/js/menu.js')
        ->prependFile($this->basePath() .'/js/jquery.colorbox.js')
        ->prependFile($this->basePath() .'/datepicker/js/jquery.ui.core.js')
        ->prependFile($this->basePath() .'/datepicker/js/jquery.ui.widget.js')
        ->prependFile($this->basePath() .'/datepicker/js/jquery.ui.datepicker.js')
        ->prependFile($this->basePath() .'/datepicker/js/jquery.ui.datepicker.js')
        ->prependFile($this->basePath() .'/js/jquery.validate.js')
        ?>
        <script>
            $(function() {
                $( "#datepicker" ).datepicker();
                $(".example1").colorbox({iframe:true, width:"80%", height:"80%"});
            });     
        </script>
    </head>
<body>
            <?php //$session_user = new Zend_Session_Namespace('login'); ?>
            <table width="" border="0" align="center" cellpadding="0" cellspacing="0" class="maintable">
                <tr>
                    <td class="topsection">
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td ><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td height="96" valign="middle">
                                  <a href="#"><img src="<?php echo $this->basePath().'images/logo.gif'; ?>" hspace="20" /></a></td>
                                            <td class="p10"><table width="0%" height="70"  border="0" align="right" cellpadding="0" cellspacing="0">
                                                    <tr><?php /*$auth = Zend_Auth::getInstance();
                                                              $username = $auth->getIdentity()->username;*/ ?>
                                                        <td height="24" valign="top" ><?php echo date('l jS \of F Y H:i:s A'); ?></td>
                                                    </tr>
                                                </table></td>
                                        </tr>
                                    </table></td>
                            </tr>
                            <tr>
                                <td height="27px"></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td ><table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                               <?php echo "<td style=\"background:url(".$this->basePath().'images/leftbg.gif'.") repeat-y; width:8px;\"></td>";?>
                                <!-- InstanceBeginEditable name="EditRegion2" -->
                                <td class="middsection"> 
                                <?php echo $this->content; ?>
                                </td>
                                <!-- InstanceEndEditable -->
                                <?php echo '<td style="background:url('.$this->basePath().'images/rightbg.gif'.') repeat-y; width:8px;"></td>';?>
                            </tr>
                        </table></td>
                </tr>
                <tr>
                    <td>
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td style="background:url(<?php echo $this->basePath().'images/bt-left.gif'; ?> ) no-repeat; height:20px; width:8px; "></td>
                                <td style="background:url(<?php echo $this->basePath().'images/bt-middle.gif'; ?> ) repeat-x; height:20px;" width="993"></td>
                                <td style="background:url(<?php echo $this->basePath().'images/bt-left.gif'; ?> ) no-repeat; height:20px; width:8px; "></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td class="bottomsection" valign="middle">
                        <table width="98%" border="0" cellspacing="5" cellpadding="0" align="center">
                            <tr>
                                <td align="left" class="bottomlink">Copyright &copy; 2012</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </body>
</html>