<script type="text/javascript">
// --------- Add and remove receivers---------
function addRow(tableID) {

  var table = document.getElementById(tableID);
  var rowCount = table.rows.length;
  if (rowCount < 8) {
    var row = table.insertRow(rowCount);

    var cell0 = row.insertCell(0);
    var element0 = document.createElement("label");
    var textnode = document.createTextNode("Receiver");
    element0.appendChild(textnode);
    cell0.appendChild(element0);
    var element1 = document.createElement("input");
    element1.type = "checkbox";
    cell0.appendChild(element1);

    var cell2 = row.insertCell(1);
    var element2 = document.createElement("input");
    element2.type = "text";
    element2.name = "receiverEmail[]";
    element2.size = "10";
    cell2.appendChild(element2);

    var cell3 = row.insertCell(2);
    var element3 = document.createElement("input");
    element3.type = "text";
    element3.name = "receiverAmount[]";
    element3.className = "smallfield";
    cell3.appendChild(element3);

    var cell4 = row.insertCell(3);
    var sel = document.createElement('select');
    sel.name = 'primaryReceiver[]';
    sel.options[0] = new Option('false', 'false');
    sel.options[1] = new Option('true', 'true');
    sel.className = "smallfield";
    cell4.appendChild(sel);

  }
}

function deleteRow(tableID) {
  try {
    var selectionMade = false;
    var table = document.getElementById(tableID);
    var rowCount = table.rows.length;
    if (rowCount > 1) {
      for ( var i = 2; i < rowCount; i++) {
        var row = table.rows[i];
        var chkbox = row.cells[0].childNodes[0];
        if (null != chkbox && true == chkbox.checked) {
          selectionMade = true;
          table.deleteRow(i);
          rowCount--;
          i--;
        }
      }
    } 
    if(!selectionMade){
      alert("Please select one or more rows to delete");
    }
  } catch (e) {
    alert(e);
  }
}

function cloneRow(tableID, maxRows) {

  var table = document.getElementById(tableID);
  var tBody = table.getElementsByTagName("tbody")[0];
  var rowCount = tBody.childElementCount;
  if (rowCount < maxRows && rowCount > 0) {
    var origRow = tBody.children[rowCount - 1];
    var row = origRow.cloneNode(true);
    row.id = getNextId(origRow.id);
    tBody.appendChild(row);
    var cells = row.getElementsByTagName("td");
    for (i = 0; i < cells.length; i++) {
      var cell = cells[i];
      var inputs = cell.getElementsByTagName("input");
      for (j = 0; j < inputs.length; j++) {
        var input = inputs[j];
        input.id = getNextId(input.id);
        if(input.type == "checkbox") {
          input.disabled = false;
        }
      }
      var inputs = cell.getElementsByTagName("select");
      for (j = 0; j < inputs.length; j++) {
        var input = inputs[j];
        input.id = getNextId(input.id);
      }      
    }
  }
}

function getNextId(id) {
  var parts = id.match(/(\D+)(\d+)$/);
  // create a unique name for the new field by incrementing
  // the number for the previous field by 1
  return parts[1] + ++parts[2];
}

// JQuery functions
function addTableRow(table) {
  // clone the last row in the table
  var $tr = $(table).find("tbody tr:last").clone();

  // get the name attribute for the input and select fields
  $tr.find("input,select").attr("name", getNextId(this.name)).attr("id",
      getNextId(this.id)).removeAttr("disabled");  
  // append the new row to the table
  $(table).find("tbody tr:last").after($tr);
}

qtipConfig = {
  style : {
    color : 'black',
    textAlign : 'left',
    border : {
      width : 7,
      radius : 5
    },
    tip : 'topLeft',
    name : 'blue'
  }
}

</script>
<?php
  
  $exception = $this->exception;
if(!empty($exception))
{
  echo "<table>
      <tr>
        <td>Type</td>
        <td>".$exception["class"]."</td>
      </tr>
      <tr>
        <td>Message</td>
        <td>".$exception["message"]."</td>
      </tr>
      <tr>
        <td>Detailed message</td>
        <td>".$exception["details_message"]."</td>
      </tr>
    </table>";
}
  ?>
<form action="" method="post">        
        <div class="note">A refund can be made against the entire
            payKey,or an individual transaction belonging to a payKey,or a
            tracking id, or a specific receiver of a payKey.</div>
        <div class="params">
          <div class="param_name">Pay key</div>
          <div class="param_value">
            <input name="payKey" id="payKey" value="" />
          </div>
        </div>
        <div class="params">
          <div class="param_name">Transaction Id</div>
          <div class="param_value">
            <input name="transactionId" id="transactionId" value="" />
          </div>
        </div>
        <div class="params">
          <div class="param_name">Tracking id</div>
          <div class="param_value">
            <input name="trackingId" id="trackingId" value="" />
          </div>
        </div>
        <div class="params">
          <div class="param_name">Currency code</div>
          <div class="param_value">
            <input name="currencyCode" id="currencyCode" value="USD" />
          </div>
        </div>
        <div class="section_header">Receiver info</div>
        <div class="note">Receiver is the party where funds are
            transferred to. A primary receiver receives a payment directly
            from the sender in a chained split payment. A primary receiver
            should not be specified when making a single or parallel split
            payment. Must set either mail or phone number</div>
        <table class="params" id="receiverTable">
          <tr>
            <th></th>
            <th>Email *</th>
            <th>Amount *</th>
            <th>Phone number</th>
            <th>Primary receiver</th>
            <th>Invoice Id</th>
            <th>Payment type</th>
            <th>Payment subtype</th>
          </tr>
          <tr id="receiverTable_0">
            <td align="left"><input type="checkbox" name="receiver_0"
              id="receiver_0" /></td>
            <td><input type="text" name="receiverEmail[]" id="receiveremail_0"
              value="platfo_1255612361_per@gmail.com">
            </td>
            <td><input type="text" name="receiverAmount[]" id="amount_0"
              value="1.0" class="smallfield">
            </td>
            <td style="display: block;"><input type="text"
              name="phoneCountry[]" id="phoneCountry_0" value=""
              class="xsmallfield"> <input type="text" name="phoneNumber[]"
              id="phoneNumber_0" value="" class="xsmallfield"> <input
              type="text" name="phoneExtn[]" id="phoneExtn_0" value=""
              class="xsmallfield">
            </td>
            <td><select name="primaryReceiver[]" id="primaryReceiver_0"
              class="smallfield">
                <option value="true">true</option>
                <option value="false" selected="selected">false</option>
            </select>
            </td>
            <td><input type="text" name="invoiceId[]" id="invoiceid_0"
              value="" class="smallfield">
            </td>
            <td><select name="paymentType[]" id="paymentType_0"
              class="smallfield">
                <option>- Select -</option>
                <option>GOODS</option>
                <option>SERVICE</option>
                <option>PERSONAL</option>
                <option>CASHADVANCE</option>
                <option>DIGITALGOODS</option>
            </select>
            </td>
            <td><input type="text" name="paymentSubType[]" id="paymentSubType"
              value="" class="smallfield">
            </td>
          </tr>
        </table>
        <a rel="receiverControls"></a>
        <table align="center">
          <tr>
            <td><a href="#receiverControls" onclick="cloneRow('receiverTable', 8)" id="Submit"><span>Add
                  Receiver </span> </a></td>
            <td><a href="#receiverControls" onclick="deleteRow('receiverTable')" id="Submit"><span>
                  Delete Receiver</span> </a></td>
          </tr>
        </table>
        <div class="submit">
          <input type="submit" value="Submit" />
        </div>
      </form>
<?php
  if(!empty($this->response)){
$ack = strtoupper($this->response->responseEnvelope->ack);
if($ack != "SUCCESS"){
  echo "<b>Error </b>";
  echo "<pre>";
  print_r($this->response);
  echo "</pre>";
} else { 
  $status = $this->response->refundInfoList->refundInfo[0]->refundStatus;
  echo "<table>";
  echo "<tr><td>Ack :</td><td><div id='Ack'>$ack</div> </td></tr>";
  echo "<tr><td>RefundStatus :</td><td><div id='RefundStatus'>$status</div></td></tr>";
  echo "</table>";
  echo "<pre>";
  print_r($this->response);
  echo "</pre>";
}
  
  // Redirect to paypal.com here
  $token = $this->response->preapprovalKey;
  $payPalURL = 'https://www.sandbox.paypal.com/webscr&cmd=_ap-preapproval&preapprovalkey='.$token;
  
  echo "<table>";
  echo "<tr><td>Ack :</td><td><div id='Ack'>$ack</div> </td></tr>";
  echo "<tr><td>PreapprovalKey :</td><td><div id='PreapprovalKey'>$token</div> </td></tr>";
  echo "<tr><td><a href=$payPalURL><b>Redirect URL to Complete Preapproval Authorization</b></a></td></tr>";
  echo "</table>";
}
    
    ?>