<script type="text/javascript">
function test()
{
    var flag=0;
    if (document.form1.current_password.value == "")
    {
          alert("Please enter password!");
          document.form1.current_password.focus();
          flag=1;
          return (false);

    }
    if (document.form1.new_password.value == "")
    {
          alert("Please enter new password!");
          document.form1.new_password.focus();
          flag=1;
          return (false);
    }
    if (document.form1.confirm_password.value == "")
    {
          alert("Please enter password to confirm!");
          document.form1.confirm_password.focus();
          flag=1;
          return (false);
    }
    if (document.form1.new_password.value != document.form1.confirm_password.value)
    {
          alert("Both Password don't match!");
          document.form1.confirm_password.focus();
          flag=1;
          return (false);
    }
    if(flag==0)
    {
        return true;
    }
}
function resetdata()
{
    document.getElementById("current_password").value="";
    document.getElementById("new_password").value="";
    document.getElementById("confirm_password").value="";
    
}
</script>
<form name="form1" action="<?php echo $this->url('admin',array('action'=>'changepassword')); ?>" method="post" >
<table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td valign="top" align="center" class="middlesection"><table width="96%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td >&nbsp;</td>
                    </tr>
                    <tr>
                      <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                <tr>
                                  <td align="left" valign="middle"><h1>Change Password</h1></td>
                                  <td align="right" valign="bottom"><table width="0%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
<!--                                        <td><a href="#" class="buttonash" onClick="resetdata();"><span> reset </span></a> </td>
                                        <td width="5"></td>
                                        <td><a onClick="javascript:if(test()){document.form1.submit();}" href="#" class="buttonash"><span> save Password </span></a></td>-->
                                      </tr>
                                    </table></td>
                                </tr>
                              </table></td>
                          </tr>
                          <tr>
                            <td class="bottomboder"><img src="<?php echo $this->basePath().'/images/ashish.gif'; ?>" height="1" /></td>
                          </tr>
                        </table></td>
                    </tr>
                    <tr>
                      <td><div  style="height: 20px;color: red; vertical-align: middle;">
                            <?php if ($this->messages) {
                                                                foreach ($this->messages as $messages) {
                                                                    echo $messages;
                                                                }
                                                            }?></div></td>
                    </tr>
                    <tr>
                      <td></td>
                    </tr>
                    <tr>
                      <td><div class="tab-content-out" style="clear:both" >
                        <div id="tabs" class="tabs" >

                             <div class="TabbedPanelsContentGroup">
		<div  class="TabbedPanelsContent">
			<div style=" border:0;" class="tab-content">
                              <div class="entry-edit">
                                <div class="tebelhd" align="left"> Admin Change Password </div>
                                <div class="fieldset" id="_generalbase_fieldset">
                                  <div class="hor-scroll" align="left">
                                    <table class="form-list" cellspacing="0">
                                      <tbody>
                                        <tr>
                                          <td class="hidden" colspan="100"><input id="_generalpath" name="general[path]" value="1" type="hidden"></td>
                                        </tr>
                                        <tr>
                                          <td class="label"><label for="current_password">Current Password<span class="required">*</span></label></td>
                                          <td class="value"><input id="current_password" name="current_password" type="password" value="" class="required-entry required-entry input-text" type="text"></td>
                                          <td></td>
                                        </tr>
                                        <tr>
                                          <td class="label"><label for="new_password">New Password<span class="required">*</span></label></td>
                                          <td class="value"><input id="new_password" name="new_password" type="password" value="" class="required-entry required-entry input-text" type="text"></td>
                                          <td></td>
                                        </tr>
                                        <tr>
                                          <td class="label"><label for="confirm_password">Confirm Password<span class="required">*</span></label></td>
                                          <td class="value"><input id="confirm_password" name="confirm_password" type="password" value="" class="required-entry required-entry input-text" type="text"></td>
                                          <td></td>
                                        </tr>
                                        <tr>
                                            <td class="label"></td>
                                            <td class="value"><a onClick="" href="javascript:history.go(-1);" class="buttonash"><span>Cancel</span></a>
                                        <a onClick="javascript:if(test()){document.form1.submit();}" href="#" class="buttonash"><span> save Password </span></a></td>
                                      
                                        </tr>
                                      </tbody>
                                    </table>
                                  </div>
                                </div>
                              </div>
                            </div>
			</div>


		</div>
               </div>
              </div></td>
              </tr>
            </table></td>
           </tr>
</table>
</form>
