<?php     
                             $this->count++;
//                            print_r($this->entries);
                            if(!empty($this->entries)){
                                
                           foreach ($this->entries as $event) {
                              
                               $friends_can_post="NO";
                               $public="NO";
                               $friends_can_share="YES";
                            if($event->friends_can_post)
                            {
                                $friends_can_post="YES";
                            }
                            if($event->public)
                                $public="YES";
                            if($event->friends_can_share)
                                $friends_can_share="YES";
                            
                            echo '<tr>
                                <td>'.$this->count++.".</td>
                                <td>$event->name</td>
                                <td>$event->location</td>
                                <td>$event->date</td>
                                <td class=\"a-right\">$friends_can_post</td>
                                <td class=\"a-right\">$friends_can_share</td>
                                <td class=\"a-right\">$public</td>
                                <td class=\"a-right\">$event->viewable_from</td>
                                <td class=\"a-right\">$event->viewable_to</td>
                                <td class=\"a-right\">$event->self_destruct</td>
                                <td class=\"a-right\"><a title=\"Click to View Event's details\" href=\"".$this->url(array('controller' => 'index', 'action' => 'viewevent', 'module' => 'admin','id'=>$this->escape($event->event_id)), '', true)."\"><img src=\"".$this->baseUrl('images/view_16x16.png')."\"></a></a>
                                    <a onclick=\"return deletecomfirm();\" title=\"Click to Delete Event\" href=\"".$this->url(array('controller' => 'index', 'action' => 'deleteevent', 'module' => 'admin','id'=>$this->escape($event->event_id)), '', true)."\"><img src=\"".$this->baseUrl('images/drop.png')."\"></a></td>
                              </tr>";
                           }
                           
                           }?>