<script type="text/javascript">
    function checkdata()
    {
        var unm=document.getElementById("username").value;
        name=trim(unm);
        if(name=="")
            {
                alert("Please enter username.");
                document.getElementById("username").value="";
                return false;
            }
            return true;
    }
function trim(str) {
        return str.replace(/^\s+|\s+$/g,"");
}
</script>

<table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
               <td height="35" align="center" class="login-hd">Forgot Password</td>
              </tr>
              <tr>
                <td><table width="100%%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td height="190">&nbsp;</td>
                    <td width="50%" valign="middle" style="padding-top:10px;" class="login">
                        <table>
                            <tr><td style="color: red">
                                    <?php
                                    if($this->flashmessenger()->hasMessages())
            foreach ($this->flashmessenger()->getMessages () as $message)
                echo $message;
                                    ?>
                                </td></tr>
                        </table>
                        <form action="<?php echo $this->url('admin',array('action'=>'forgotpassword')); ?>" method="post" onsubmit="return checkdata();">
                        <table width="0%" border="0" align="center" cellpadding="0" cellspacing="5">
                        <tr>
                    <td>User Name : </td>
                    <td><input type="text" size="20" name="username" id="username" ></td>
                </tr>
                <tr>
                    <td></td>
                    <td><span class="buttons" >
                            <input id="submit" type="submit" value="submit" name="submit">
</span></td>
                  </tr>
                   <tr>
   <td colspan="2" align="center"><a href="<?php echo $this->url('admin',array('action'=>'index')); ?>"><strong>Back To Login?</strong></a></td>
                </tr>
                    </table>
                        </form>
                    </td>
                  </tr>
                </table></td>
              </tr>
            </table>
