<script type="text/javascript">
function actionFilterwithcompleteview(action,id){

            var page=document.getElementById('page_complete').value;
            //document.getElementById('action_name').value=action;
            limit=parseInt(document.getElementById('limit_complete').value);
            document.getElementById('page_complete').value=parseInt(page)+1;
            newlimit = parseInt(page);// * parseInt('<?php echo ADMIN_QUERY_LIMIT-1; ?>');
            //newlimit = parseInt(page) * parseInt('<?php //echo 2-1; ?>');
            if(document.getElementById('viewmorecomplete')){
                document.getElementById('load_div_complete').style.display="block";
                document.getElementById('viewmorecomplete').style.display="none";
            }
            admin=<?php echo ADMIN_QUERY_LIMIT; ?>;
            x=limit/admin;
            y=parseInt(x);
            if(x>y){
                y++;
            }
            if(y<=newlimit) {
                document.getElementById('viewmorecomplete').style.display="none";
            }
            
//            var url ='<?php // echo $this->url(array('action'=>'manageeventspagination')); ?>'+'/page/'+page;
//            alert('page='+page+' limit '+limit+' new limit='+newlimit+' url='+url);
                $.ajax({
                    type: "POST",
                    url: url,
                     success: function(retdiv) {
                        document.getElementById('load_div_complete').style.display="none";
                        document.getElementById('viewmorecomplete').style.display="block";
                        if($.trim(retdiv)=='' || y<=newlimit) {
                            document.getElementById('viewmorecomplete').style.display="none";
                        }
                        $('#question_data').append(retdiv);
                    }
                });
    }
function deletecomfirm(){
        var r=confirm("Do You Realy Wat to Delete This Item ! ");
        if (r==true)
            return true;
  
        else
            return false;
    }

function submitform()
{
  document.myform.submit();
}
  function searchtest(){
  
      var name,id='',page='';

      name=document.getElementById('user').value;
      var url = "<?php echo $this->basePath() . "/admin/action/manageevents"; ?>";

      if(name==""){
          return false;
      }
//      url = url+"/id/"+id;
//      url = url+"/page/"+page;
      if(name!=""){
        url = url+"/userid/"+name;
      }
      window.location = url;
}
</script>



<?php // echo $this->url('admin',array('action'=>'filtereventbyuser','id'=>'','page'=>'','userid'=>'12'));
                                     ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td style="background:url('<?php echo $this->basePath().'/images/leftbg.gif'; ?>') repeat-y; width:8px;"></td>
          <!-- InstanceBeginEditable name="EditRegion2" -->
          <td class="middlesection"><table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td>&nbsp;</td>
              </tr>
              <tr>
                <td class="p10"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td align="left" valign="middle"><h1>Manage Events</h1></td>
                            <td align="right" valign="bottom"><h4 style="color: #4B5974;">Total Events : <?php echo $this->event_total;?></h4></td>
                          </tr>
                        </table></td>
                    </tr>
                    <tr>
                      <td class="bottomboder"><img src="<?php echo $this->basePath().'/images/ashish.gif'; ?>" height="1" /></td>
                    </tr>
                  </table></td>
              </tr>
              <tr>
                  <td class="p10"><div style="width:960px;">
                          <table>
                                  <tr><td><span>User</span></td>
                                      <td>
                                          <select name="user" id="user">
                                              <?php
//                                              $coun=0;echo "<pre>";
                                              if (isset($this->users) && count($this->users) > 0) {
                                                  foreach ($this->users as $user){
//                                                      echo $coun++;print_r($user);
                                                      if(strcasecmp($user->user_id,$this->user_id)==0)
                                                              echo '<option value="' . $user->user_id . '" selected="selected">' . $user->username . '</option>';
                                                      else
                                                          echo '<option value="' . $user->user_id . '">' . $user->username . '</option>';
                                                  }
                                              }
                                              ?>
                                          </select>
                                      </td>
                                          <td><a href="javascript:searchtest()" class="buttonash"><span>Get Event</span></a></td></tr> 
                                          
                              </table>

                        <div  style="height: 20px;color: red; vertical-align: middle;">
                            <?php if ($this->messages) {
                                                                foreach ($this->messages as $messages) {
                                                                    echo $messages;
                                                                }
                                                            }
                                               if($this->flashmessenger()->hasMessages())
            foreach ($this->flashmessenger()->getMessages () as $message)
                echo $message;
                                                          
                                                            ?></div>
                    <div id="productGrid">
                       
                      <div class="grid">
                        <div class="">
                           <table class="data" id="productGrid_table" cellspacing="0">
                              <input type="hidden" name="page_complete" id="page_complete" value="2"/>
                            <input type="hidden" name="limit_complete" id="limit_complete" value="<?php if(!empty ($this->event_total)) echo $this->event_total; else echo "0"; ?>"/>
<!--                            <input type="hidden" name="filter" id="filter" value="<?php // if(!empty ($this->filter)) echo $this->filter;?>"/>-->
<!--                            <col class="a-center" widtd="20" />
                            <col widtd="50" />
                            <col />
                            <col widtd="60" />
                            <col widtd="100" />
                            <col widtd="80" />
                            <col widtd="100" />
                            <col widtd="100" />
                            <col widtd="70" />
                            <col widtd="70" />
                            <col widtd="100" />
                            <col widtd="50" />-->
                            <thead>
                              <tr class="headings" style="height: 25px;">

                                <th width="3%"><span class="sort-title">Id</span></th>
                                <th width="20%"><span class="sort-title">Event Name</span></th>
                                <th width="15%"><span class="sort-title">Location</span></th>
                                <th width="10%"><span class="sort-title">Date</span></th>
                                <th width="3%"><span class="sort-title">Friends can Post</span></th>
                                <th width="3%"><span class="sort-title">Friends can Share</span></th>
                                <th width="5%"><span class="sort-title">Public</span></th>
                                <th width="5%"><span class="sort-title">Viewable From</span></th>
                                <th width="5%"><span class="sort-title">Viewable To</span></th>
                                <th width="5%"><span class="sort-title">Self Destruct</span></th>
                                <th width="25%"><span class="sort-title">Action</span></th>

                            </thead>
                            
                            <?php     
                            $count=1;
//                            print_r($this->entries);
                            if(!empty($this->entries) && count($this->entries)!=0){
                                echo "<tbody id=\"question_data\">";
                           foreach ($this->entries as $event) {
//                               print_r($event);
                               $friends_can_post="NO";
                               $public="NO";
                               $friends_can_share="YES";
                            if($event->friends_can_post)
                            {
                                $friends_can_post="YES";
                            }
                            if($event->public)
                                $public="YES";
                            if($event->friends_can_share)
                                $friends_can_share="YES";
                            
                            echo '<tr>
                                <td>'.$count++.".</td>
                                <td>".$event->name."</td>
                                <td>".$event->location."</td>
                                <td>".$event->date."</td>
                                <td class=\"a-right\">".$friends_can_post."</td>
                                <td class=\"a-right\">$friends_can_share</td>
                                <td class=\"a-right\">$public</td>
                                <td class=\"a-right\">".$event->viewable_from."</td>
                                <td class=\"a-right\">".$event->viewable_to."</td>
                                <td class=\"a-right\">".$event->self_destruct."</td>
                                <td class=\"a-right\"><a title=\"Click to View Event's details\" href=\"".$this->url('admin',array('action' => 'viewevent','id'=>$this->escapeHtml($event->event_id)))."\"><img src=\"".$this->basePath().'/images/view_16x16.png'."\"></a></a>
                                <a onclick=\"return deletecomfirm();\" title=\"Click to Delete Event\" href=\"".$this->url('admin',array('action' => 'deleteevent','id'=>$this->escapeHtml($event->event_id)))."\"><img src=\"".$this->basePath().'/images/drop.png'."\"></a></td>
                              </tr>";
                           }
                           echo "</tbody>";
                           }
                           else
                               echo "<tbody><tr><td  colspan=\"11\" style=\"height: 20px;color: red; vertical-align: middle;\">No Record Found</td></tr></tbody>" ;
                                    ?>
                            </table>
                            <div class="paging">
                    <?= ( count($this->entries) > 0 ) ? $this->paginationControl($this->entries, 'Sliding', 'admin/index/pagerformanageevents.phtml') : ""; ?>
                </div>
                     
                        </div>
                      </div>
                    </div>
               </div></td>
              </tr>
            </table></td>
          <!-- InstanceEndEditable -->
          <td style="background:url('<?php echo $this->basePath().'/images/rightbg.gif'; ?>') repeat-y; width:8px;"></td>
        </tr>
      </table>