<table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td valign="top" align="center" class="middlesection"><table width="96%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td >&nbsp;</td>
                    </tr>
                    <tr>
                      <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                <tr>
                                  <td align="left" valign="middle"><h1>User Details</h1></td>
                                  <td align="right" valign="bottom">

                                  </td>
                                </tr>
                              </table></td>
                          </tr>
                          <tr>
                            <td class="bottomboder"><img src="<?php echo $this->basePath().'/images/ashish.gif'; ?>" height="1" /></td>
                          </tr>
                        </table></td>
                    </tr>
                    <tr>
                      <td><div  style="height: 20px;color: red; vertical-align: middle;">
                            <?php if ($this->messages) {
                                                                foreach ($this->messages as $messages) {
                                                                    echo $messages;
                                                                }
                                                            }?></div></td>
                    </tr>
                    <tr>
                      <td></td>
                    </tr>
                    <tr>
                      <td><div class="tab-content-out" style="clear:both" >
                        <div id="tabs" class="tabs" >

                             <div class="TabbedPanelsContentGroup">
		<div  class="TabbedPanelsContent">
			<div style=" border:0;" class="tab-content">
                              <div class="entry-edit">
                                <div class="tebelhd" align="left"> General Information </div>
                                <div class="fieldset" id="_generalbase_fieldset">
                                  <div class="hor-scroll" align="left">
                                    <table class="form-list" cellspacing="0">
                                      <tbody>
                                        <?php                                          
                                          if(!empty($this->entries)) {
                                          ?>
                                        <tr>
                                          <td class="hidden" colspan="100"><input id="_generalpath" name="general[path]" value="1" type="hidden"></td>
                                        </tr>
                                        <tr>
                                          <td class="label"><label for="name">Name : </label></td>
                                          <td class="value"> <?php echo $this->entries->username; ?></td>
                                          <td></td>
                                        </tr>
                                        <tr>
                                          <td class="label"><label for="">Role : </label></td>
                                          <td class="value"><?php if($this->entries->role == 2){echo 'User';}
                                          else if($this->entries->role == 1){echo 'Supper Admin';}
                                          else if($this->entries->role == 3){echo 'Admin';}?></td>
                                          <td></td>
                                        </tr>
                                        <tr>
                                          <td class="label"><label for="">Email Address :</label></td>
                                          <td class="value"><?php echo $this->entries->email_address; ?></td>
                                          <td></td>
                                        </tr>
                                        <tr>
                                          <td class="label"><label for="">Disable account :</label></td>
                                          <td class="value"><?php echo $this->entries->disable_account ? 'Active' : "Deactive" ; ?></td>
                                          <td></td>
                                        </tr>
                                        <tr>
                                          <td class="label"><label for="">Profile Photo :</label></td>
                                          <td class="value"><?php echo  ($this->entries->profile_photo)? "YES" : "NO"; ?></td>
                                          <td></td>
                                        </tr>
                                        <tr>
                                          <td class="label"><label for="">Facebook Name :</label></td>
                                          <td class="value"><?php echo $this->entries->facebook_username; ?></td>
                                          <td></td>
                                        </tr>
                                        <tr>
                                          <td class="label"><label for="">Twitter Name :</label></td>
                                          <td class="value"><?php echo $this->entries->twitter_username; ?></td>
                                          <td></td>
                                        </tr>
                                            <?php }else 
                                                echo "<tr><td  style=\"height: 20px;color: red; vertical-align: middle;\">No Record Found</td></tr>" ;
                                                ?>
                                      </tbody>
                                    </table>
                                      
                                  </div>
                                </div>
                              </div>
                            </div>
			</div>
                                 

		</div>
               </div>
              </div></td>
              </tr>
            </table></td>
           </tr>
</table>
<table align="center"><tr><td><a onClick="" href="javascript:history.go(-1);<?php //  echo $this->url('admin',array('action'=>'manageusers')); ?>" class="buttonash"><span>Back</span></a></td></tr></table>