<?php 
use Guzzle\Http\Client;
use Zend\Session\Container;

$domain = "http://d1ckv7o9k6o3x9.cloudfront.net/";

error_log("OUTPUT XML ----> " . $this->xml);
if (isset($this->xml)) {
	$xml  = new SimpleXMLElement($this->xml);
} else {
	echo("xml not found");
}
?>

<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Memreas</title>

<!--Custom css-->
<link href="/memreas/css/style.css" rel="stylesheet" type="text/memreas/css">
<link rel="stylesheet" type="text/memreas/css" href="/memreas/css/elastislide.css" />
<link href="/memreas/css/jquery.mCustomScrollbar.css" rel="stylesheet" />

<!--Bootstrap Css-->
<link href="/memreas/css/bootstrap.min.css" rel="stylesheet" type="text/memreas/css">

<!--jQuery Lybrary-->
<script src="/memreas/js/jquery.js"></script>
<script src="/memreas/js/modernizr.custom.17475.js"></script>

<!--Bootstrap jQuery-->
<script src="/memreas/js/bootstrap.min.js"></script>

<!--Backgound Strecher-->
<script type="text/javascript" src="/memreas/js/bgstretcher.js"></script>
<script type="text/javascript">
$(document).ready(function(){
$(document).bgStretcher({
			images: ['/memreas/img/bg.jpg'],
			imageWidth: 1366, imageHeight: 700
		});
	});


$(document).ready(function(){
	$(window).unload(function() {
	  alert('Handler for .unload() called.');
	});
});

window.onbeforeunload = function() {
	jQuery.logout();
	alert("onbeforeunload");
    return "Are you sure??";
};
</script>

</head>

<body>
<!-- Begin : Container -->
<div class="container">
  <!-- Begin : Header -->
  <div class="row-fluid">
  	<header>
      <h1 id="logo"><a href="index.html">memreas</a></h1>
      <input name="input"type="text" class="search_bar" value="@person, #discover" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == '@person, #discover')this.value = '';"/>
      <div class="pro-info">
      	<figure class="pro-pic"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
        <div class="pro-name">User Name</div>
      </div>
    </header>
  </div>
  <!-- End : Header -->
  <!-- Begin : Content -->
  	<div class="row-fluid content">
      <div class="span1">
      	<!-- Begin : Nav -->
      	<nav>
          <ul>
          	<li><a href="#"><img src="/memreas/img/gallery.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/queue.png" alt=""></a></li>
            <li><a href="#" class="active"><img src="/memreas/img/share.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/memreas.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/more.png" alt=""></a></li>
          </ul>
        </nav>
        <!-- End : Nav -->
      </div>
      <div class="span11">
      <div class="span9">
      	<div class="span6">
      	  <aside id="left">
            <figure class="event">
              <div class="image-preview">
            	<img id="preview" data-preview="img/large/1.jpg" alt="" />
		      </div>
            </figure>
          </aside>
        </div>
        <div class="clear-2"></div>
        <div class="span6">
          <div id="content_1" class="right">
            <ul>
              <li class="clearfix">
              	<figure class="pro-pics"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                <div class="pro-names">User Name</div>
              </li>
              <li>
              	<figure class="pro-pics"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                <textarea name="your sign or comments here" cols="" rows="" 
                onfocus="if(this.value==this.defaultValue)this.value='';" 
                onblur="if(this.value=='')this.value=this.defaultValue;">your sign or comments here</textarea>
              </li>
              <li>
              	<figure class="pro-pics"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                <textarea name="your sign or comments here" cols="" rows="" 
                onfocus="if(this.value==this.defaultValue)this.value='';" 
                onblur="if(this.value=='')this.value=this.defaultValue;">your sign or comments here</textarea>
              </li>
              <li>
              	<figure class="pro-pics"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                <textarea name="your sign or comments here" cols="" rows="" 
                onfocus="if(this.value==this.defaultValue)this.value='';" 
                onblur="if(this.value=='')this.value=this.defaultValue;">your sign or comments here</textarea>
              </li>
              <li>
              	<figure class="pro-pics"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                <textarea name="your sign or comments here" cols="" rows="" 
                onfocus="if(this.value==this.defaultValue)this.value='';" 
                onblur="if(this.value=='')this.value=this.defaultValue;">your sign or comments here</textarea>
              </li>
              <li>
              	<figure class="pro-pics"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                <textarea name="your sign or comments here" cols="" rows="" 
                onfocus="if(this.value==this.defaultValue)this.value='';" 
                onblur="if(this.value=='')this.value=this.defaultValue;">your sign or comments here</textarea>
              </li>
              <li>
              	<figure class="pro-pics"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                <textarea name="your sign or comments here" cols="" rows="" 
                onfocus="if(this.value==this.defaultValue)this.value='';" 
                onblur="if(this.value=='')this.value=this.defaultValue;">your sign or comments here</textarea>
              </li>
            </ul>
          </div>
        </div>
        <div class="clear"></div>
        <div class="row-fluid">
          <ul id="carousel" class="elastislide-list">
<?php  
foreach( $xml->listallmediaresponse->medias->{'media'} as $media ) {

		/* - sample
		$content = simplexml_load_string('<content><![CDATA[Hello, world!]]></content>', null, LIBXML_NOCDATA);
		
		Request :-
		<xml>
		    <listallmedia>
		        <event_id>1</event_id>
		        <user_id>1</user_id>
		        <device_id>123456</device_id>
		        <limit>2</limit>
				<page>1</page>
		    </listallmedia>
		</xml>
		Response :-
		<xml>
		    <listallmediaresponse>
		        <medias>
					<page> 1 </page>
		            <media> 
		            	<media_id>1</media_id>
						<main_media_url><![CDATA[url]]></main_media_url>
						<media_url_79x80><![CDATA[url]]></media_url_79x80>
						<media_url_98x78><![CDATA[url]]></media_url_98x78>
						<media_url_448x306><![CDATA[url]]></media_url_448x306>
	                	<media_name>abc.wmv</media_name>
    	            	<is_downloaded>1</is_downloaded>
	        	        <type>image</type>
            		</media>
    		    </medias>
		    </listallmediaresponse>
		</xml>
		*/

?>          
			<li data-preview="<?php echo $domain . $media->main_media_url; ?>"><a href="<?php echo $domain . $media->main_media_url; ?>"><img src="<?php echo $domain . $media->main_media_url; ?>"  height="25" width="25" alt="image01" /></a></li>
<?php          
}          
?>          
<!--
			<li data-preview="img/large/1.jpg"><a href="#"><img src="/memreas/img/small/1.jpg" alt="image01" /></a></li>
			<li data-preview="img/large/2.jpg"><a href="#"><img src="/memreas/img/small/2.jpg" alt="image02" /></a></li>
            <li data-preview="img/large/1.jpg"><a href="#"><img src="/memreas/img/small/1.jpg" alt="image01" /></a></li>
			<li data-preview="img/large/2.jpg"><a href="#"><img src="/memreas/img/small/2.jpg" alt="image02" /></a></li>
            <li data-preview="img/large/1.jpg"><a href="#"><img src="/memreas/img/small/1.jpg" alt="image01" /></a></li>
			<li data-preview="img/large/2.jpg"><a href="#"><img src="/memreas/img/small/2.jpg" alt="image02" /></a></li>
            <li data-preview="img/large/1.jpg"><a href="#"><img src="/memreas/img/small/1.jpg" alt="image01" /></a></li>
			<li data-preview="img/large/2.jpg"><a href="#"><img src="/memreas/img/small/2.jpg" alt="image02" /></a></li>
            <li data-preview="img/large/1.jpg"><a href="#"><img src="/memreas/img/small/1.jpg" alt="image01" /></a></li>
			<li data-preview="img/large/2.jpg"><a href="#"><img src="/memreas/img/small/2.jpg" alt="image02" /></a></li>
            <li data-preview="img/large/1.jpg"><a href="#"><img src="/memreas/img/small/1.jpg" alt="image01" /></a></li>
			<li data-preview="img/large/2.jpg"><a href="#"><img src="/memreas/img/small/2.jpg" alt="image02" /></a></li>
            <li data-preview="img/large/1.jpg"><a href="#"><img src="/memreas/img/small/1.jpg" alt="image01" /></a></li>
			<li data-preview="img/large/2.jpg"><a href="#"><img src="/memreas/img/small/2.jpg" alt="image02" /></a></li>
            <li data-preview="img/large/1.jpg"><a href="#"><img src="/memreas/img/small/1.jpg" alt="image01" /></a></li>
			<li data-preview="img/large/2.jpg"><a href="#"><img src="/memreas/img/small/2.jpg" alt="image02" /></a></li>
            <li data-preview="img/large/1.jpg"><a href="#"><img src="/memreas/img/small/1.jpg" alt="image01" /></a></li>
			<li data-preview="img/large/2.jpg"><a href="#"><img src="/memreas/img/small/2.jpg" alt="image02" /></a></li>
            <li data-preview="img/large/1.jpg"><a href="#"><img src="/memreas/img/small/1.jpg" alt="image01" /></a></li>
			<li data-preview="img/large/2.jpg"><a href="#"><img src="/memreas/img/small/2.jpg" alt="image02" /></a></li>
-->
		  </ul>
        </div>
        <div class="row-fluid">
          <div class="menu clearfix">
          	<ul>
          	  <li><a href="#" class="active"><img src="/memreas/img/syns.png" alt=""></a></li>
              <li><a href="#"><img src="/memreas/img/like.png" alt=""></a></li>
              <li><a href="#"><img src="/memreas/img/comment.png" alt=""></a></li>
              <li><a href="#"><img src="/memreas/img/sound.png" alt=""></a></li>
              <li><a href="#"><img src="/memreas/img/report.png" alt=""></a></li>
          	</ul>
          </div>
        </div>
      </div>
      <div class="span3">
      	<section id="ad">
          <div class="adbox">Your <br>Advertisement <br>space </div>
          <div class="adbox">Your <br>Advertisement <br>space </div>
          <div class="adbox-port">Your <br>Advertisement <br>space </div>
          <div class="adbox-port">Your <br>Advertisement <br>space </div>
        </section>
      </div>
      <div class="row-fluid"><div class="ad"><img src="/memreas/img/ad.jpg"></div></div>
      </div>
    </div>
  <!-- End : Content -->
  <!-- Begin : Footer -->
  <!-- End : Footer -->
</div>
<footer>&copy; 2013 memreas, llc. All rights reserved.</footer>
<!-- End : Container -->
	<script type="text/javascript" src="/memreas/js/jquery.elastislide.js"></script>
	<script type="text/javascript">
			
			// example how to integrate with a previewer

			var current = 0,
				$preview = $( '#preview' ),
				$carouselEl = $( '#carousel' ),
				$carouselItems = $carouselEl.children(),
				carousel = $carouselEl.elastislide( {
					current : current,
					minItems : 3,
					onClick : function( el, pos, evt ) {

						changeImage( el, pos );
						evt.preventDefault();

					},
					onReady : function() {

						changeImage( $carouselItems.eq( current ), current );
						
					}
				} );

			function changeImage( el, pos ) {

				$preview.attr( 'src', el.data( 'preview' ) );
				$carouselItems.removeClass( 'current-img' );
				el.addClass( 'current-img' );
				carousel.setCurrent( pos );

			}

	</script>
	<!-- custom scrollbars plugin -->
	<script src="/memreas/js/jquery.mCustomScrollbar.concat.min.js"></script>
	<script>
		(function($){
			$(window).load(function(){
				$("#content_1").mCustomScrollbar({
					scrollButtons:{
						enable:true
					}
				});
				//ajax demo fn
				$("a[rel='load-content']").click(function(e){
					e.preventDefault();
					var $this=$(this),
						url=$this.attr("href");
					$this.addClass("loading");
					$.get(url,function(data){
						$this.removeClass("loading");
						$("#content_1 .mCSB_container").html(data); //load new content inside .mCSB_container
						$("#content_1").mCustomScrollbar("update"); //update scrollbar according to newly loaded content
						$("#content_1").mCustomScrollbar("scrollTo","top",{scrollInertia:200}); //scroll to top
					});
				});
				$("a[rel='append-content']").click(function(e){
					e.preventDefault();
					var $this=$(this),
						url=$this.attr("href");
					$this.addClass("loading");
					$.get(url,function(data){
						$this.removeClass("loading");
						$("#content_1 .mCSB_container").append(data); //append new content inside .mCSB_container
						$("#content_1").mCustomScrollbar("update"); //update scrollbar according to newly appended content
						$("#content_1").mCustomScrollbar("scrollTo","h2:last",{scrollInertia:2500,scrollEasing:"easeInOutQuad"}); //scroll to appended content
					});
				});
			});
		})(jQuery);
	</script>
</body>
</html>
