<?php 
use Guzzle\Http\Client;
use Zend\Session\Container;

$domain = "http://d1ckv7o9k6o3x9.cloudfront.net/";

error_log("OUTPUT XML ----> " . $this->xml);
if (isset($this->xml)) {
	$xml  = new SimpleXMLElement($this->xml);
}
?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Memreas</title>

<!--Custom css-->
<link href="/memreas/css/style.css" rel="stylesheet" type="text/memreas/css">
<link href="/memreas/css/jquery.mCustomScrollbar.css" rel="stylesheet" />
<link rel="stylesheet" href="/memreas/css/swipebox.css">

<!--Bootstrap Css-->
<link href="/memreas/css/bootstrap.min.css" rel="stylesheet" type="text/memreas/css">

<!--jQuery Lybrary-->
<script src="/memreas/memreas/js/jquery.js"></script>
<script src="/memreas/memreas/js/modernizr.custom.17475.js"></script>

<!--Bootstrap jQuery-->
<script src="/memreas/memreas/js/bootstrap.min.js"></script>

<!--Backgound Strecher-->
<script type="text/javascript" src="/memreas/memreas/js/bgstretcher.js"></script>
<script type="text/javascript">
$(document).ready(function(){
$(document).bgStretcher({
			images: ['/memreas/img/bg.jpg'],
			imageWidth: 1366, imageHeight: 700
		});
	});
</script>

</head>

<body>
<!-- Begin : Container -->
<div class="container">
  <!-- Begin : Header -->
  <div class="row-fluid">
  	<header>
      <h1 id="logo"><a href="index.html">memreas</a></h1>
      <input name="input"type="text" class="search_bar" value="@person, #discover" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == '@person, #discover')this.value = '';"/>
      <div class="pro-info">
      	<figure class="pro-pic"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
        <div class="pro-name">User Name</div>
      </div>
    </header>
  </div>
  <!-- End : Header -->
  <!-- Begin : Content -->
  	<div class="row-fluid content">
      <div class="span1">
      	<!-- Begin : Nav -->
      	<nav>
          <ul>
          	<li><a href="#"><img src="/memreas/img/gallery.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/queue.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/share.png" alt=""></a></li>
            <li><a href="#" class="active"><img src="/memreas/img/memreas.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/more.png" alt=""></a></li>
          </ul>
        </nav>
        <!-- End : Nav -->
      </div>
      <div class="span11">
      <div class="span9">
      	<div class="row-fluid">
          <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
          <div class="pro-names2">User Name</div>
        </div>
        <div class="row-fluid">
          <ul id="content_1" class="pics">
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
              </ul>
          <a class="black_btn_skin f-left" href="#">add media</a>
          <a class="black_btn_skin f-right" href="#">add friends</a>
        </div>
      </div>
      <div class="span3">
      	<section id="ad">
          <div class="adbox">Your <br>Advertisement <br>space </div>
          <div class="adbox">Your <br>Advertisement <br>space </div>
          <div class="adbox-port">Your <br>Advertisement <br>space </div>
          <div class="adbox-port">Your <br>Advertisement <br>space </div>
        </section>
      </div>
      <div class="row-fluid"><div class="ad"><img src="/memreas/img/ad.jpg" alt=""></div></div>
      </div>
    </div>
  <!-- End : Content -->
</div>
  <!-- Begin : Footer -->
  <footer>&copy; 2013 memreas, llc. All rights reserved.</footer>
  <!-- End : Footer -->
<!-- End : Container -->

<!-- custom scrollbars plugin -->
	<script src="/memreas/memreas/js/jquery.mCustomScrollbar.concat.min.js"></script>
	<script>
		(function($){
			$(window).load(function(){
				$("#content_1").mCustomScrollbar({
					scrollButtons:{
						enable:true
					}
				});
				//ajax demo fn
				$("a[rel='load-content']").click(function(e){
					e.preventDefault();
					var $this=$(this),
						url=$this.attr("href");
					$this.addClass("loading");
					$.get(url,function(data){
						$this.removeClass("loading");
						$("#content_1 .mCSB_container").html(data); //load new content inside .mCSB_container
						$("#content_1").mCustomScrollbar("update"); //update scrollbar according to newly loaded content
						$("#content_1").mCustomScrollbar("scrollTo","top",{scrollInertia:200}); //scroll to top
					});
				});
				$("a[rel='append-content']").click(function(e){
					e.preventDefault();
					var $this=$(this),
						url=$this.attr("href");
					$this.addClass("loading");
					$.get(url,function(data){
						$this.removeClass("loading");
						$("#content_1 .mCSB_container").append(data); //append new content inside .mCSB_container
						$("#content_1").mCustomScrollbar("update"); //update scrollbar according to newly appended content
						$("#content_1").mCustomScrollbar("scrollTo","h2:last",{scrollInertia:2500,scrollEasing:"easeInOutQuad"}); //scroll to appended content
					});
				});
			});
		})(jQuery);
	</script>
<!-- custom swipebox plugin -->    
	<script src="/memreas/memreas/js/jquery.swipebox.min.js"></script>
	<script type="text/javascript">
		jQuery(function($) {
			$(".swipebox").swipebox();
		});
	</script>
</body>
</html>
