<?php
error_log("Inside memreas-me-friends.phtml");
error_log("getcwd ----> " . getcwd());
error_log("DIR ----> " . dirname(__DIR__));
?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>memreas</title>

<!--Custom css-->
<link href="/memreas/css/style.css" rel="stylesheet" type="text/memreas/css">
<link href="/memreas/css/jquery.mCustomScrollbar.css" rel="stylesheet" />
<link rel="stylesheet" href="/memreas/css/swipebox.css">

<!--Bootstrap Css-->
<link href="/memreas/css/bootstrap.min.css" rel="stylesheet" type="text/memreas/css">

<!--jQuery Lybrary-->
<script src="/memreas/js/jquery.js"></script>
<script src="/memreas/js/modernizr.custom.17475.js"></script>

<!--Bootstrap jQuery-->
<script src="/memreas/js/bootstrap.min.js"></script>

<!--Backgound Strecher-->
<script type="text/javascript" src="/memreas/js/bgstretcher.js"></script>
<script type="text/javascript">
$(document).ready(function(){
$(document).bgStretcher({
			images: ['/memreas/img/bg.jpg'],
			imageWidth: 1366, imageHeight: 700
		});
	});
</script>

</head>

<body>
<!-- Begin : Container -->
<div class="container">
  <!-- Begin : Header -->
  <div class="row-fluid">
  	<header>
      <h1 id="logo"><a href="index.html">memreas</a></h1>
      <input name="input"type="text" class="search_bar" value="@person, #discover" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == '@person, #discover')this.value = '';"/>
      <div class="pro-info">
      	<figure class="pro-pic"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
        <div class="pro-name">User Name</div>
      </div>
    </header>
  </div>
  <!-- End : Header -->
  <!-- Begin : Content -->
  	<div class="row-fluid content">
      <div class="span1">
      	<!-- Begin : Nav -->
      	<nav>
          <ul>
          	<li><a href="#"><img src="/memreas/img/gallery.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/queue.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/share.png" alt=""></a></li>
            <li><a href="#" class="active"><img src="/memreas/img/memreas.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/more.png" alt=""></a></li>
          </ul>
        </nav>
        <!-- End : Nav -->
      </div>
      <div class="span11">
      <div class="span9">
      	<div class="row-fluid">
<ul id="tabs">
    <li><a href="#" title="tab1">me</a></li>
    <li><a href="#" title="tab2">friends</a></li>
    <li><a href="#" title="tab3">public</a></li>
</ul>

<div id="tab-content"> 
    <div id="tab1" class="hideCls">
              <ul id="content_1" class="pics scrollClass">
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
              </ul>  
          <a class="black_btn_skin f-left" href="#">add memreas</a>
          <a class="black_btn_skin f-right" href="#">add friends</a>  
    </div>
    <div id="tab2" class="hideCls">
         <ul id="content_1" class="pics scrollClass">
         		<section class="row-fluid clearfix">
                  <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                  <aside class="pro-names2">Friend Name</aside>
                </section>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <section class="row-fluid clearfix">
                  <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                  <aside class="pro-names2">Friend Name</aside>
                </section>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <section class="row-fluid clearfix">
                  <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                  <aside class="pro-names2">Friend Name</aside>
                </section>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <section class="row-fluid clearfix">
                  <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                  <aside class="pro-names2">Friend Name</aside>
                </section>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <section class="row-fluid clearfix">
                  <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                  <aside class="pro-names2">Friend Name</aside>
                </section>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <section class="row-fluid clearfix">
                  <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                  <aside class="pro-names2">Friend Name</aside>
                </section>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <section class="row-fluid clearfix">
                  <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                  <aside class="pro-names2">Friend Name</aside>
                </section>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <section class="row-fluid clearfix">
                  <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                  <aside class="pro-names2">Friend Name</aside>
                </section>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
              </ul>  
          <a class="black_btn_skin f-center" href="#">add memreas</a> 
    </div>
    <div id="tab3" class="hideCls">
        <ul id="content_1" class="pics scrollClass">
         		<section class="row-fluid clearfix">
                  <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                  <aside class="pro-names2">Friend Name</aside>
                </section>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <section class="row-fluid clearfix">
                  <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                  <aside class="pro-names2">Friend Name</aside>
                </section>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <section class="row-fluid clearfix">
                  <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                  <aside class="pro-names2">Friend Name</aside>
                </section>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <section class="row-fluid clearfix">
                  <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                  <aside class="pro-names2">Friend Name</aside>
                </section>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <section class="row-fluid clearfix">
                  <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                  <aside class="pro-names2">Friend Name</aside>
                </section>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <section class="row-fluid clearfix">
                  <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                  <aside class="pro-names2">Friend Name</aside>
                </section>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <section class="row-fluid clearfix">
                  <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                  <aside class="pro-names2">Friend Name</aside>
                </section>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <section class="row-fluid clearfix">
                  <figure class="pro-pics2"><img src="/memreas/img/profile-pic-2.jpg" alt=""></figure>
                  <aside class="pro-names2">Friend Name</aside>
                </section>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
              </ul> 
          <a class="black_btn_skin f-center" href="#">add memreas</a> 
    </div>
</div>
        </div>
      </div>
      <div class="span3">
      	<section id="ad">
          <div class="adbox">Your <br>Advertisement <br>space </div>
          <div class="adbox">Your <br>Advertisement <br>space </div>
          <div class="adbox-port">Your <br>Advertisement <br>space </div>
          <div class="adbox-port">Your <br>Advertisement <br>space </div>
        </section>
      </div>
      <div class="row-fluid"><div class="ad"><img src="/memreas/img/ad.jpg" alt=""></div></div>
      </div>
    </div>
  <!-- End : Content -->
  <!-- Begin : Footer -->
  <!-- End : Footer -->
</div>
<footer>&copy; 2013 memreas, llc. All rights reserved.</footer>
<!-- End : Container -->


<!-- custom scrollbars plugin -->
	<script src="/memreas/js/jquery.mCustomScrollbar.concat.min.js"></script>
	<script>
	
		(function($){
			$(window).load(function(){
			
			$("ul.scrollClass").mCustomScrollbar({
					scrollButtons:{
						enable:true
					}
				});
				
				
				
				
			$("#tab-content div.hideCls").hide(); // Initially hide all content
			$("#tabs li:first").attr("id","current"); // Activate first tab
			$("#tab-content div:first").fadeIn(); // Show first tab content*/
			
			$('#tabs a').click(function(e) {
				
				e.preventDefault();        
				$("#tab-content div.hideCls").hide(); //Hide all content
				$("#tabs li").attr("id",""); //Reset id's
				$(this).parent().attr("id","current"); // Activate this
				$('#' + $(this).attr('title')).fadeIn(); // Show content for current tab
			});

			
				
				
				//ajax demo fn
				$("a[rel='load-content']").click(function(e){
					
					e.preventDefault();
					var $this=$(this),
						url=$this.attr("href");
					$this.addClass("loading");
					$.get(url,function(data){
						$this.removeClass("loading");
						$("ul.scrollClass .mCSB_container").html(data); //load new content inside .mCSB_container
						$("ul.scrollClass").mCustomScrollbar("update"); //update scrollbar according to newly loaded content
						$("ul.scrollClass").mCustomScrollbar("scrollTo","top",{scrollInertia:200}); //scroll to top
					});
				});
				$("a[rel='append-content']").click(function(e){
					e.preventDefault();
					var $this=$(this),
						url=$this.attr("href");
					$this.addClass("loading");
					$.get(url,function(data){
						$this.removeClass("loading");
						$("ul.scrollClass .mCSB_container").append(data); //append new content inside .mCSB_container
						$("ul.scrollClass").mCustomScrollbar("update"); //update scrollbar according to newly appended content
						$("ul.scrollClass").mCustomScrollbar("scrollTo","h2:last",{scrollInertia:2500,scrollEasing:"easeInOutQuad"}); //scroll to appended content
					});
				});
			});
		})(jQuery);
	</script>
    
    <!-- custom swipebox plugin -->    
	<script src="/memreas/js/jquery.swipebox.min.js"></script>
	<script type="text/javascript">
		jQuery(function($) {
			$(".swipebox").swipebox();
		});
	</script>

</body>
</html>
