<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Memreas</title>

<!--Custom css-->
<link href="/memreas/css/style.css" rel="stylesheet" type="text/memreas/css">
<link href="/memreas/css/jquery.mCustomScrollbar.css" rel="stylesheet" />
<link rel="stylesheet" href="/memreas/css/swipebox.css">

<!--Bootstrap Css-->
<link href="/memreas/css/bootstrap.min.css" rel="stylesheet" type="text/memreas/css">
<link href="/memreas/css/datepicker.css" rel="stylesheet" type="text/memreas/css">

<!--jQuery Lybrary-->
<script src="/memreas/js/jquery.js"></script>
<script src="/memreas/js/modernizr.custom.17475.js"></script>

<!--Bootstrap jQuery-->
<script src="/memreas/js/bootstrap.min.js"></script>
<script src="/memreas/js/bootstrap-datepicker.js"></script>
<script type="text/javascript">
$(function() {
$( "#datepicker" ).datepicker();
$( "#datepicker-1" ).datepicker();
$( "#datepicker-2" ).datepicker();
$( "#datepicker-3" ).datepicker();
});
</script>


<!--Backgound Strecher-->
<script type="text/javascript" src="/memreas/js/bgstretcher.js"></script>
<script type="text/javascript">
$(document).ready(function(){
$(document).bgStretcher({
			images: ['/memreas/img/bg.jpg'],
			imageWidth: 1366, imageHeight: 700
		});
	});
</script>

</head>

<body>
<!-- Begin : Container -->
<div class="container">
  <!-- Begin : Header -->
  <div class="row-fluid">
  	<header>
      <h1 id="logo"><a href="index.html">memreas</a></h1>
      <input name="input"type="text" class="search_bar" value="@person, #discover" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == '@person, #discover')this.value = '';"/>
      <div class="pro-info">
      	<figure class="pro-pic"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
        <div class="pro-name">User Name</div>
      </div>
    </header>
  </div>
  <!-- End : Header -->
  <!-- Begin : Content -->
  	<div class="row-fluid content">
      <div class="span1">
      	<!-- Begin : Nav -->
      	<nav>
          <ul>
          	<li><a href="#"><img src="/memreas/img/gallery.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/queue.png" alt=""></a></li>
            <li><a href="#" class="active"><img src="/memreas/img/share.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/memreas.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/more.png" alt=""></a></li>
          </ul>
        </nav>
        <!-- End : Nav -->
      </div>
      <div class="span11">
      <div class="span9">
      	<div class="row-fluid">
<ul id="tabs">
    <li><a href="#" title="tab1" style="padding: .7em 1em;">memreas details</a></li>
    <li><a href="#" title="tab2">media</a></li>
    <li><a href="#" title="tab3">friends</a></li>
</ul>
    <div id="tab-content">
      <div id="tab1" class="hideCls">
        <ul id="content_1" class="share_memreas_details scrollClass">
        <li>
        <label class="textfield_names">name :</label>
        <input name="input" type="text" class="share-txtfield" value="sample" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';"/>
        </li>
        <li>
        <label class="textfield_names">date :</label>
        <input name="input" type="text" id="datepicker" class="share-txtfield date-picker" value="" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == '#')this.value = '';"/>
        </li>
        <li>
        <label class="textfield_names">location :</label>
        <input name="input3" type="text" class="share-txtfield" value="address or current location" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'address or current location')this.value = '';"/>
        </li>
        <li>
         <input id="demo_box_1" class="css-checkbox" type="checkbox" checked="checked"/>
      	 <label for="demo_box_1" name="demo_lbl_1" class="css-label margin-none" >friends can post pics/videos</label>
        </li>
        <li>
         <input id="demo_box_2" class="css-checkbox" type="checkbox" checked="checked"/>
      	 <label for="demo_box_2" name="demo_lbl_2" class="css-label margin-none" >friends can add Friends</label>
        </li>
        <li>
         <input id="demo_box_3" class="css-checkbox" type="checkbox" checked="checked"/>
      	 <label for="demo_box_3" name="demo_lbl_3" class="css-label margin-none" >public</label>
        </li>
        <li>
         <input id="demo_box_4" class="css-checkbox" type="checkbox" checked="checked"/>
      	 <label for="demo_box_4" name="demo_lbl_4" class="css-label margin-none" >viewable :</label>
         <input name="input" type="text" id="datepicker-1" class="date-picker" value="from" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'from')this.value = '';"/>
         <input name="input" type="text" id="datepicker-2" class="date-picker" value="to" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'to')this.value = '';"/>
        </li>
        <li>
         <input id="demo_box_5" class="css-checkbox" type="checkbox" checked="checked"/>
      	 <label for="demo_box_5" name="demo_lbl_5" class="css-label margin-none" >self destruct :</label>
         <input name="input" type="text" id="datepicker-3" class="share-txtfield-2 date-picker" value="" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == '')this.value = '';"/>       
        </li>
        </ul>
      	    <a class="black_btn_skin f-center" href="#">next</a> 
            <a class="black_btn_skin" href="#">cancel</a>
        </div>
      	  <div id="tab2" class="hideCls">
      	    <ul id="content_1" class="share scrollClass">
      	      <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-3.jpg" class="swipebox" title="photo-3"><img src="/memreas/img/small-pic-3.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
                <li><a href="/memreas/img/large-pic-2.jpg" class="swipebox" title="photo-2"><img src="/memreas/img/small-pic-2.jpg" alt=""></a></li>
    	      </ul>
              <div class="comment">
              <ul>
              <li>
              <div class="comment-txt">add a comment</div>
              </li>
              <li>
                <input name="input2" type="text" class="comment_txtfield" value="your comments here" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'your comments here')this.value = '';"/>
                </li>
                </ul>    
              </div>
      	    <a class="black_btn_skin f-center" href="#">next</a> 
            <a class="black_btn_skin f-middle" href="#">cancel</a>
            </div>
      	  <div id="tab3" class="hideCls">
      	      <ul id="content_1" class="share_friends_contents scrollClass">
      	        <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
      	        <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
      	        <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	          </li>
      	        <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	          </li>
      	        <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	          </li>
      	        <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	          </li>
      	        <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
      	        <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
    	        </ul>
      	      <ul class="share_friends_check_box">
      	        <li>
      	          <input id="demo_box_6" class="css-checkbox" type="checkbox" checked="checked" />
      	          <label for="demo_box_6" name="demo_lbl_6" class="css-label">make this a group</label>
                  <input name="input" type="text" class="share-txtfield-3" value="group name here" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'group name here')this.value = '';"/>
                  </li>
    	        </ul>
      	    <a class="black_btn_skin f-center" href="#">ok</a> <a class="black_btn_skin f-middle" href="#">cancel</a> 
    	  </div>
          </div>
      	</div>
      </div>
      <div class="span3">
      	<section id="ad">
          <div class="adbox">Your <br>Advertisement <br>space </div>
          <div class="adbox">Your <br>Advertisement <br>space </div>
          <div class="adbox-port">Your <br>Advertisement <br>space </div>
          <div class="adbox-port">Your <br>Advertisement <br>space </div>
        </section>
      </div>
      <div class="row-fluid"><div class="ad"><img src="/memreas/img/ad.jpg" alt=""></div></div>
      </div>
    </div>
  <!-- End : Content -->
  <!-- Begin : Footer -->
  <!-- End : Footer -->
</div>
<footer>&copy; 2013 memreas, llc. All rights reserved.</footer>
<!-- End : Container -->


<!-- custom scrollbars plugin -->
	<script src="/memreas/js/jquery.mCustomScrollbar.concat.min.js"></script>
	<script>
	
		(function($){
			$(window).load(function(){
			
			$("ul.scrollClass").mCustomScrollbar({
					scrollButtons:{
						enable:true
					}
				});
				
				
				
				
			$("#tab-content div.hideCls").hide(); // Initially hide all content
			$("#tabs li:first").attr("id","current"); // Activate first tab
			$("#tab-content div:first").fadeIn(); // Show first tab content*/
			
			$('#tabs a').click(function(e) {
				
				e.preventDefault();        
				$("#tab-content div.hideCls").hide(); //Hide all content
				$("#tabs li").attr("id",""); //Reset id's
				$(this).parent().attr("id","current"); // Activate this
				$('#' + $(this).attr('title')).fadeIn(); // Show content for current tab
			});

			
				
				
				//ajax demo fn
				$("a[rel='load-content']").click(function(e){
					
					e.preventDefault();
					var $this=$(this),
						url=$this.attr("href");
					$this.addClass("loading");
					$.get(url,function(data){
						$this.removeClass("loading");
						$("ul.scrollClass .mCSB_container").html(data); //load new content inside .mCSB_container
						$("ul.scrollClass").mCustomScrollbar("update"); //update scrollbar according to newly loaded content
						$("ul.scrollClass").mCustomScrollbar("scrollTo","top",{scrollInertia:200}); //scroll to top
					});
				});
				$("a[rel='append-content']").click(function(e){
					e.preventDefault();
					var $this=$(this),
						url=$this.attr("href");
					$this.addClass("loading");
					$.get(url,function(data){
						$this.removeClass("loading");
						$("ul.scrollClass .mCSB_container").append(data); //append new content inside .mCSB_container
						$("ul.scrollClass").mCustomScrollbar("update"); //update scrollbar according to newly appended content
						$("ul.scrollClass").mCustomScrollbar("scrollTo","h2:last",{scrollInertia:2500,scrollEasing:"easeInOutQuad"}); //scroll to appended content
					});
				});
			});
		})(jQuery);
	</script>
    
    <!-- custom swipebox plugin -->    
	<script src="/memreas/js/jquery.swipebox.min.js"></script>
	<script type="text/javascript">
		jQuery(function($) {
			$(".swipebox").swipebox();
		});
	</script>
</body>
</html>
